### ISSUE TITLE
CMake needs to be constrained for trilinos-for-albany

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#13]
We're getting:
```
1 error found in build log:
  >> 5    CMake Error at CMakeLists.txt:62 (CMAKE_MINIMUM_REQUIRED):
     6      CMake 3.23.0 or higher is required.  You are running version 3.20.3
     7    
     8    
     9    -- Configuring incomplete, errors occurred!

See build log for details:
  /lustre/scratch4/turquoise/.mdt1/trhille/spack_temp/spack-stage/spack-stage-trilinos-for-albany-develop-jkvnaiv3aovrxaaoexun7nndsz7bvjcb/spack-build-out.txt

==> Warning: Skipping build of albany-develop-mrq6dnnp2dqwptb2rhnty4veov32try4 since trilinos-for-albany-develop-jkvnaiv3aovrxaaoexun7nndsz7bvjcb failed
==> Error: albany-develop-mrq6dnnp2dqwptb2rhnty4veov32try4: Package was not installed
```
See https://github.com/E3SM-Project/mache/pull/109#issuecomment-1450519781

This is pretty annoying because the minimum version should be constrained by the package itself so we don't waste minutes to hours building spack environments, only to have them ultimately fail.

**Comment by xylar** [comment]
@ikalash, could you add this constraint to the package?

**Comment by ikalash** [comment]
@xylar : yes - this is a recent change for Trilinos.  I'm on foreign travel through Mar. 11 and likely will not get a chance to do it until I return.  Sorry about the delay.

**Comment by ikalash** [comment]
@xylar : I just pushed a change that should fix this. Could you please test it?  I just pushed directly to develop branch.  The machines where I build Albany/Trilinos using spack don't have too low of a cmake so it's not 100% trivial for me to test this myself.

**Comment by xylar** [comment]
@ikalash, your fix looks good to me.  I don't have an easy way to test it at the moment either because I modified my spack environments to stop using system cmake.  I will at least update the spack branch I'm using to include the new commit so I can make sure it doesn't break things.

**Comment by ikalash** [comment]
Sounds great, thanks in advance for testing.
