### ISSUE TITLE
Add option to build Albany via spack with "mesh depends on parameters" turned on

### ISSUE THREAD

**Issue by ikalash** [E3SM-Project/spack#14]
### Summary

Feature request by @mperego for Gonzalo.

### Rationale

N/A

### Description

N/A

### Additional information

N/A

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikalash** [comment]
@mperego : I have added this option.  You can turn it on by building Albany with the +mesh_depends_on_params flag.  It is off by default.

Let me know if you're interested in other options like MESH_DEPENDS_ON_SOLUTION.

**Comment by mperego** [comment]
Thanks @ikalash! This is good. We actually removed the option `MESH_DEPENDS_ON_SOLUTION`.

**Comment by ikalash** [comment]
Ah OK.  Here are instructions for building Albany with spack, if you wanted to share them: https://github.com/sandialabs/Albany/wiki/Building-Albany-using-Spack .  You'd have to add the new option as one of the + when building the code.

**Comment by mperego** [comment]
Thanks! Is the cxx17 option still needed? Now that should be automatically set by Trilinos.

**Comment by ikalash** [comment]
Yes that option is gone.  I will remove it from the documentation.
