### ISSUE TITLE
Rebase `develop` onto `v0.20.1` tag

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#17]
The v0.20.1 tag of spack was released in July:
https://github.com/spack/spack/releases/tag/v0.20.1

I've been holding off on rebasing until E3SM-Unified 1.9.0 was released, which happened yesterday.

I have a test branch with the (completely painless) rebase here:
https://github.com/xylar/spack/tree/rebase-onto-0.20.1

**Comment by xylar** [comment]
@ikalash, @kliegeois, you are the other folks who typically care about this.  Are you okay with me rebasing now?  Or would you like me to wait?

**Comment by ikalash** [comment]
It's fine with me to rebase now.  The spack nightlies have been running correctly for awhile.

**Comment by xylar** [comment]
Okay, I'll go for it!

**Comment by xylar** [comment]
Done!
