### ISSUE TITLE
Suggested updates to Albany package

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#18]
@bartgol wrote on Slack:
> I'm not a spack dev, but I think adding
> ```
>             options.extend(
>                 [
>                     define("CMAKE_C_COMPILER", spec["mpi"].mpicc),
>                     define("CMAKE_CXX_COMPILER", spec["mpi"].mpicxx),
>                 ]
>             )
> ```
> to `albany/package.py` may be enough. (I copied those lines from the trilinos `package.py` file)
> 
> btw, I see in trilinos/package.py that those lines are guarded by
> ```
>  if "+mpi" in spec:
> ```
> which makes sense. However, I would then expect to find `+mpi` in one of the lines
> ```
> depends_on("trilinos-for-albany@develop ...)
> ```
> in `albany/package.py`. But instead, I don't see any such spec modifier. I do see
> ```
> depends_on("mpi")
> ```
> but my guts tell me that this does not trigger [this](https://github.com/E3SM-Project/spack/blob/140b2d627a3efe9bb4e098b5da0f474f6ed963a7/var/spack/repos/builtin/packages/trilinos/package.py#L784C8-L784C27) piece of code in the trilinos recipe...

@ikalash, what do you think?

**Comment by ikalash** [comment]
I don't have the context to follow this.  Perhaps it makes sense to have a short Teams call?  I'm free after 3PM PT today, or next week would work too.

**Comment by bartgol** [comment]
My suggestion may not be correct for GPU builds. It is still unclear to me what's the "official" trilinos policy is to build on nvidia gpu systems. I know of 2 ways:
1. Set mpicxx (or whatever mpi ompiler) as CMAKE_CXX_COMPILER, and set the OMPI_CXX (or analogue for other mpi distros) to point to nvcc wrapper
2. Set nvcc_wrapper as CMAKE_CXX_COMPILER, and edit it to have mpicxx (or whatever mpi ccompiler) as host compiler

If we want this recipe to be only for CPU systems, then my original suggestion may be fine. If we want the spack recipe to work on GPU systems as well, then this needs to be thought through a bit more.

**Comment by xylar** [comment]
@bartgol (and @ikalash), is this issue from a year ago still relevant?

**Comment by ikalash** [comment]
Good question.  I don't remember.  Do you @bartgol ?  I guess you opened the issue.

**Comment by bartgol** [comment]
I don't remember my flow of thoughts. I think albany's package.yaml is probably fine, since we always build with mpi enabled, given that we require trilinos-for-albany, and that package explicitly says `depends_on('mpi')`. So I think everthing is consistent, so long as mpi is explicitly added as a required dep of trilinos-for-albany.

If one had to switch to use `trilinos` rather than `trilinos-for-albany` though, things may be quite different...

**Comment by xylar** [comment]
I'm going to close this.  It seems like maybe opening a PR would be better if someone wants to make improvements.
