### ISSUE TITLE
Modify spack Albany package to enable building with Omega_h enabled

### ISSUE THREAD

**Issue by ikalash** [E3SM-Project/spack#24]
### Summary

Need to modify spack Albany build to enable one to turn on Omega_h for mesh adaptivity.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikalash** [comment]
I did this (tagging @bartgol ).  To build with omegah enabled you add +omegah to the Albany build line.  The code built just fine.  It would be good at some point to try building MALI on top of this Albany to make sure things are ok.  Perhaps @xylar can do this.  I will go ahead and close the issue tomorrow provided that the nightly spack build is clean (which it should be based on my tests).

**Comment by bartgol** [comment]
@xylar FYI, Omega_h support is still in a very early stage (lots of features still missing), so this is not a priority by any stretch. IMHO, we can wait a few more weeks, until I get a few more features supported (and tested) in standalone Albany.

**Comment by ikalash** [comment]
@bartgol : I agree with the above.

**Comment by xylar** [comment]
Thanks for the heads up.  I will definitely try this out but I won't have time for a little bit.  I may enlist help from @matthewhoffman, @trhille or someone else from the team.
