### ISSUE TITLE
Rebase develop onto 0.21.1

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#25]
@ikalash, I think it's a good time to rebase onto the latest spack release (0.21.1).

I have a branch here that does that:
https://github.com/xylar/spack/tree/rebase-onto-0.21.1

The rebase only had conflicts for trilinos for one commit (explicitly adding cmake as a dependency to add a lower bound) and fixing that seemed quite straightforward.  Also, we don't actually use that the `trilinos` package, we use `trilinos-for-albany` so I don't think there's any risk at all.

Let me know when the timing is right for me to force-push to `develop`.  Obviously, let me know if you see any problems either in advance or during testing.

**Comment by ikalash** [comment]
Thanks for doing this!  The spack nightly testing has been clean.  I think you can push and then we can see if there are problems tomorrow.  Alternatively, if you prefer, I can test your fork before the merge.

**Comment by xylar** [comment]
Okay, I just force-pushed.  I'm guessing this might be too late for the nightly tests but let me know how they go (both tonight and tomorrow night).

**Comment by ikalash** [comment]
Right, it's too late for the tests.  I will check tomorrow morning.

**Comment by ikalash** [comment]
It looks like there are issues with PyAlbany building now in the spack build, after @xylar's merge/force push.  The errors look as follows: 

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

80 errors found in build log:
     1675    In file included from /tmp/ikalash/spack-stage/spack-stage-albany-
             develop-arkng5gny6zpzlqkykyarnjtdjjau3ml/spack-build-arkng5g/tpls/
             omega_h/pybind11-src/include/pybind11/attr.h:13,
     1676                     from /tmp/ikalash/spack-stage/spack-stage-albany-
             develop-arkng5gny6zpzlqkykyarnjtdjjau3ml/spack-build-arkng5g/tpls/
             omega_h/pybind11-src/include/pybind11/pybind11.h:45,
     1677                     from /tmp/ikalash/spack-stage/spack-stage-albany-
             develop-arkng5gny6zpzlqkykyarnjtdjjau3ml/spack-src/pyAlbany/src/Al
             bany_Pybind11_Include.hpp:1,
     1678                     from /tmp/ikalash/spack-stage/spack-stage-albany-
             develop-arkng5gny6zpzlqkykyarnjtdjjau3ml/spack-src/pyAlbany/src/Al
             bany_Pybind11_Comm.hpp:14,
     1679                     from /tmp/ikalash/spack-stage/spack-stage-albany-
             develop-arkng5gny6zpzlqkykyarnjtdjjau3ml/spack-src/pyAlbany/src/Al
             bany_Pybind11_Comm.cpp:7:
     1680    /tmp/ikalash/spack-stage/spack-stage-albany-develop-arkng5gny6zpzl
             qkykyarnjtdjjau3ml/spack-build-arkng5g/tpls/omega_h/pybind11-src/i
             nclude/pybind11/cast.h: In function 'std::string pybind11::detail:
             :error_string()':
  >> 1681    /tmp/ikalash/spack-stage/spack-stage-albany-develop-arkng5gny6zpzl
             qkykyarnjtdjjau3ml/spack-build-arkng5g/tpls/omega_h/pybind11-src/i
             nclude/pybind11/cast.h:446:36: error: invalid use of incomplete ty
             pe 'PyFrameObject' {aka 'struct _frame'}
     1682      446 |                 "  " + handle(frame->f_code->co_filename).
             cast<std::string>() +
     1683          |                                    ^~
```
@kliegeois do you know what would cause this?  It isn't happening in the regular Albany builds.

**Comment by xylar** [comment]
@kliegeois, let me know if there's anything I can do to help fix this.

**Comment by ikalash** [comment]
Just to follow up, I talked to @kliegeois today, and he is busy until end of Feb. with another project that is ending.  I think it's OK to defer fixing this, as long as it does not fall through the cracks.  I therefore will keep this issue open.

**Comment by xylar** [comment]
Okay, I reopened the issue.

**Comment by kliegeois** [comment]
Hi all, I finally have the time to look into that.

@ikalash was the error generated with this spack command?

```
spack --insecure install --dirty --keep-stage albany@develop+mpas+py
```

**Comment by kliegeois** [comment]
OK, I was finally able to reproduce the error using
```
spack --insecure install --keep-stage albany@develop+mpas+py
```
I am trying to fix it.

**Comment by ikalash** [comment]
@kliegeois : yes that configure line will work.  Sorry for not responding, I am on foreign travel.  Thank you for looking into this!

**Comment by kliegeois** [comment]
@ikalash no worries!
The issue seems to be related to an unsupported combination of python and pybind11.
I need to try one or two things but it will take me some time as changing the python version triggers the compilation of python itself, numpy, spicy, mpi4py, and PyAlbany.

**Comment by kliegeois** [comment]
@ikalash @xylar the PR listed above fixes the issue.
