### ISSUE TITLE
`develop` has been rebased onto v0.21.2

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#28]
@ikalash and @kliegeois, I just wanted to let you know that I rebased `develop` onto https://github.com/spack/spack/releases/tag/v0.21.2.  I think this won't cause trouble.  The rebase was clean.  I just wanted to let you know to keep an eye on the tests over the next few days.
https://github.com/xylar/spack/tree/old_develop points to the old `develop` just in case we have to revert something.

**Comment by ikalash** [comment]
Thanks for the heads up @xylar .  The nightly spack build is failing but that's because of a Trilinos issue introduced in the past could of days.  Hopefully that will be resolved soon.

**Comment by ikalash** [comment]
The spack nightly built is clean, modulo something that @mperego is looking at with one of the PyAlbany tests.

**Comment by xylar** [comment]
Okay, great!
