### ISSUE TITLE
Rebase onto 0.22

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#29]
Spack v0.22 was released earlier this week.  Is now a good time to rebase?
https://github.com/spack/spack/releases/tag/v0.22.0

@ikalash
@kliegeois

**Comment by xylar** [comment]
I have a rebase branch here:
https://github.com/E3SM-Project/spack/tree/rebase-onto-0.22

The rebase was pretty clean (some conflicts in the SCORPIO, MOAB and NCO packages that were easy to fix).

**Comment by ikalash** [comment]
Thanks for doing this @xylar .  I think it's OK to merge in.  I can check tomorrow that the nightlies are all clean.

**Comment by xylar** [comment]
Done! 🤞🏻
