### ISSUE TITLE
Rebase onto 0.22.1

### ISSUE THREAD

**Issue by altheaden** [E3SM-Project/spack#30]
This is an update for release tag 0.22.1 which I did with @xylar. It is on my branch: https://github.com/altheaden/spack/tree/rebase-onto-v0.22.1

The rebase was completely clean so we don't have any concerns, but let me know if you have any. Otherwise, I can force push to update develop in the next day or two.

The spack release is: https://github.com/spack/spack/releases/tag/v0.22.1

@ikalash
@kliegeois

**Comment by xylar** [comment]
@altheaden just got hired as a postbac to work with us at LANL on all things infrastructure.  This is her exciting foray into spack!

**Comment by kliegeois** [comment]
Welcome @altheaden and no concerns on my side but we should probably wait for @ikalash to comment as well.

**Comment by xylar** [comment]
@ikalash, it seems like you were probably out last week.  If you're checking messages, could you let us know if you're okay with us proceeding with the rebase?  If we don't hear anything, we'll probably go ahead with it tomorrow (Wednesday).  Hopefully, your nightly tests will reveal any potential problems that causes.

**Comment by ikalash** [comment]
There was an unrelated issue preventing Albany from building.  I think I fixed it today.  If the nightlies are clean tomorrow, we can merge this.

**Comment by xylar** [comment]
Great, @ikalash, keep us posted!

**Comment by ikalash** [comment]
Will do - I’ll post back tomorrow when I’ve had the chance to look at the outcomes of the tests (I’m on foreign travel in Europe so it may be at an odd hour).

**Comment by ikalash** [comment]
@xylar : you can go ahead and merge now.

**Comment by xylar** [comment]
@ikalash, great, thank you!

**Comment by xylar** [comment]
@altheaden just did this.  Thanks @kliegeois and @ikalash!
