### ISSUE TITLE
Rebase onto 0.22.2

### ISSUE THREAD

**Issue by altheaden** [E3SM-Project/spack#32]
Hello! I've created an update for release tag v0.22.2, on my fork: https://github.com/altheaden/spack/tree/rebase-onto-0.22.2

The rebase was completely clean without having to make any manual changes, but let me know if you have any concerns. Assuming there are no issues, I can force push this to `develop` whenever works for you guys.

The spack release is: https://github.com/spack/spack/releases/tag/v0.22.2

@ikalash
@kliegeois

**Comment by xylar** [comment]
Looks great to me!  Thanks @altheaden!

**Comment by xylar** [comment]
@ikalash and @kliegeois, I think we'll probably go ahead and push the rebased branch later today unless we hear from either of you that the timing is bad.  I'd rather not have this sit too long and start losing track of new changes to `develop`.

**Comment by ikalash** [comment]
@xylar : that's fine.  Albany got broken today, just as an FYI, so the nightlies for the spack might not pass.  @bartgol I believe is fixing the problem.

**Comment by bartgol** [comment]
The fix went in earlier today. The code now builds on my machine.

**Comment by ikalash** [comment]
Thank you @bartgol !  I will close the Albany issue related to this if things are clean tomorrow.

**Comment by xylar** [comment]
Okay, sounds fine.  We'll do the rebase tomorrow to not cause any extra confusion.

**Comment by ikalash** [comment]
Sounds like a good plan.  I'll comment here that things are clean once they are, hopefully.

**Comment by ikalash** [comment]
The nightlies are clean so you can go ahead and push the merge.

**Comment by altheaden** [comment]
Will do, thank you!

**Comment by xylar** [comment]
Great, thanks @ikalash and @altheaden!
