### ISSUE TITLE
Rebase onto spack v0.23.0

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/spack#33]
Spack 0.23.0 has been released:
https://github.com/spack/spack/releases/tag/v0.23.0

I have a branch where I did the rebase as best I could:
https://github.com/xylar/spack/tree/rebase-onto-0.23.0
It was messier than usual, in large part because they have added new dependencies on languages like:
```
depends_on("cxx", type="build") 
```

This means that the results could be messy and require some fixes.

**Comment by xylar** [comment]
@ikalash, when would be a good time to force-push my rebase branch to `develop` and see how things go?  Would this week be better than next?

**Comment by ikalash** [comment]
@xylar : yesterday Trilinos in the spack build got broken b/c of some changes to the syntax for specifying a Kokkos option.  I just fixed it.  Can we wait till the nightly spack build is clean again?  Hopefully it will be tonight.  I will ping you when it is.

**Comment by xylar** [comment]
Yep, sounds fine.  Keep me posted.  I'll cherry-pick your latest commits onto my rebased branch so nothing gets lost.

**Comment by ikalash** [comment]
I haven't forgotten about this.  The nightly spack build is still down due to an omega-h + Kokkos issue (https://github.com/sandialabs/Albany/issues/1092#issuecomment-2504591843).  I'll let you know when it's resolved.  Hopefully next weke.

**Comment by xylar** [comment]
Thanks for the update. No rush.

**Comment by ikalash** [comment]
It's OK to merge now.

**Comment by xylar** [comment]
Great, think you for letting me know.  I'll double check that nothing has changed and force-push now.

**Comment by xylar** [comment]
Done!
